# Generated by Django 5.0.4 on 2024-04-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_student_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='picfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=50)),
                ('purl', models.ImageField(upload_to='')),
            ],
            options={
                'db_table': 'picfile',
            },
        ),
    ]
